apiVersion: v1
kind: Secret
metadata:
  namespace: production
  name: rdicidr
  # A bootstrap token Secret usually resides in the kube-system namespace
stringData:
  password: On3H1torL3sS # required field for kubernetes.io/basic-auth
